### ISSUE TITLE
There is minor typo.   

### ISSUE THREAD

**Issue by minwoominwoominwoo7** [ROBOTIS-GIT/turtlebot3_manipulation_simulations#13]
Hi~ I find some typo. :) 

https://github.com/ROBOTIS-GIT/turtlebot3_manipulation_simulations/blob/master/turtlebot3_manipulation_gazebo/launch/turtlebot3_manipulation_gazebo.launch
```bash
<include file="$(find turtlebot3_manipulation_gazebo)/launch/turtlebot3_manipulation_controller.launch/">
-> 
<include file="$(find turtlebot3_manipulation_gazebo)/launch/turtlebot3_manipulation_controller.launch"/>
```

**Comment by ROBOTIS-Will** [comment]
Thank you! There was a PR(#12) for this issue and merged into the master :)
